# Generated by Django 5.2.3 on 2025-06-18 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='users.department')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='commune',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.commune'),
            preserve_default=False,
        ),
    ]
