# Generated by Django 5.2.3 on 2025-06-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_contact_department_commune_contact_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accessible_departments',
            field=models.ManyToManyField(blank=True, related_name='accessible_users', to='users.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='administrated_communes',
            field=models.ManyToManyField(blank=True, related_name='admins', to='users.commune'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='administrated_departments',
            field=models.ManyToManyField(blank=True, related_name='admins', to='users.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('admin_global', 'Admin Global'), ('admin_department', 'Admin Département'), ('admin_commune', 'Admin Commune'), ('user', 'Utilisateur')], default='user', max_length=20),
        ),
    ]
