# Generated by Django 5.2.3 on 2025-06-19 13:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_phone_number_historicalcommune_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='notes',
            new_name='observation',
        ),
        migrations.RenameField(
            model_name='historicalcontact',
            old_name='notes',
            new_name='observation',
        ),
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[users.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='contact',
            name='reminder',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[users.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='reminder',
            field=models.TextField(blank=True),
        ),
    ]
